# See: https://docs.github.com/code-security/dependabot/working-with-dependabot/dependabot-options-reference#about-the-dependabotyml-file
version: 2

updates:
  # Configure check for outdated GitHub Actions actions in workflows.
  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/dependabot/README.md
  # See: https://docs.github.com/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
  - package-ecosystem: github-actions
    directory: /.github/workflows
    assignees:
      - per1234
    open-pull-requests-limit: 100
    schedule:
      cronjob: 0 12 * * *
      interval: cron
    labels:
      - "topic: infrastructure"

  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 100
    schedule:
      cronjob: 0 14 * * *
      interval: cron
    labels:
      - "topic: infrastructure"
    assignees:
      - per1234

  - package-ecosystem: pip
    directory: /
    open-pull-requests-limit: 100
    schedule:
      cronjob: 0 15 * * *
      interval: cron
    labels:
      - "topic: infrastructure"
    assignees:
      - per1234
