# Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-npm-task.md
name: Check npm

# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/check-npm-task.ya?ml"
      - "**/.npmrc"
      - "**/package.json"
      - "**/package-lock.json"
      - "Taskfile.ya?ml"
  pull_request:
    paths:
      - ".github/workflows/check-npm-task.ya?ml"
      - "**/.npmrc"
      - "**/package.json"
      - "**/package-lock.json"
      - "Taskfile.ya?ml"
  schedule:
    # Run every Tuesday at 8 AM UTC to catch breakage resulting from changes to the JSON schema.
    - cron: "0 8 * * TUE"
  workflow_dispatch:
  repository_dispatch:

permissions:
  contents: read

jobs:
  validate:
    name: validate (${{ matrix.project.path }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        project:
          - path: .

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Validate package.json
        run: |
          task \
            --silent \
            npm:validate \
            PROJECT_PATH="${{ matrix.project.path }}"

  check-sync:
    name: check-sync (${{ matrix.project.path }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        project:
          - path: .

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Install npm dependencies
        run: |
          task \
            npm:install-deps \
            PROJECT_PATH="${{ matrix.project.path }}"

      - name: Check package-lock.json
        run: |
          git \
            diff \
              --color \
              --exit-code \
              "${{ matrix.project.path }}/package-lock.json"
